# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookify.api:
    build:
      context: "X:\\Repos\\Bookify"
      dockerfile: "Bookify.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Bookify.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookifyapi:dev"
    ports: []
    volumes:
    - "X:\\Repos\\Bookify\\Bookify.Api:/app:rw"
    - "X:\\Repos\\Bookify:/src:rw"
    - "C:\\Users\\realb\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
